# Generated by Django 4.2.4 on 2023-08-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salute_dEncyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animador',
            name='profesion',
            field=models.CharField(default='Sin profesión especificada', max_length=50),
        ),
        migrations.AddField(
            model_name='cineasta',
            name='profesion',
            field=models.CharField(default='Sin profesión especificada', max_length=50),
        ),
        migrations.AddField(
            model_name='escritor',
            name='profesion',
            field=models.CharField(default='Sin profesión especificada', max_length=50),
        ),
        migrations.AddField(
            model_name='escultor',
            name='profesion',
            field=models.CharField(default='Sin profesión especificada', max_length=50),
        ),
        migrations.AddField(
            model_name='fotografo',
            name='profesion',
            field=models.CharField(default='Sin profesión especificada', max_length=50),
        ),
        migrations.AddField(
            model_name='grabador',
            name='profesion',
            field=models.CharField(default='Sin profesión especificada', max_length=50),
        ),
        migrations.AddField(
            model_name='ilustrador',
            name='profesion',
            field=models.CharField(default='Sin profesión especificada', max_length=50),
        ),
        migrations.AddField(
            model_name='musico',
            name='profesion',
            field=models.CharField(default='Sin profesión especificada', max_length=50),
        ),
        migrations.AddField(
            model_name='pintor',
            name='profesion',
            field=models.CharField(default='Sin profesión especificada', max_length=50),
        ),
    ]
