# Generated by Django 4.2.4 on 2023-08-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salute_dEncyclopedia', '0002_animador_profesion_cineasta_profesion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('nacimiento', models.DateField()),
                ('profesion', models.CharField(default='Sin profesión especificada', max_length=50)),
            ],
        ),
    ]
