# Generated by Django 4.2.4 on 2023-09-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salute_cHome', '0002_perfilartista_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilartista',
            name='nombre_completo',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
