# Generated by Django 4.2.4 on 2023-09-03 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salute_cHome', '0003_perfilartista_nombre_completo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilArtista',
        ),
    ]
