# Generated by Django 4.2.4 on 2023-09-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salute_dArtist', '0002_actor_musico_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='email',
            field=models.EmailField(default='Ningun email registrado', max_length=254),
        ),
        migrations.AddField(
            model_name='animador',
            name='email',
            field=models.EmailField(default='Ningun email registrado', max_length=254),
        ),
        migrations.AddField(
            model_name='cineasta',
            name='email',
            field=models.EmailField(default='Ningun email registrado', max_length=254),
        ),
        migrations.AddField(
            model_name='escritor',
            name='email',
            field=models.EmailField(default='Ningun email registrado', max_length=254),
        ),
        migrations.AddField(
            model_name='escultor',
            name='email',
            field=models.EmailField(default='Ningun email registrado', max_length=254),
        ),
        migrations.AddField(
            model_name='fotografo',
            name='email',
            field=models.EmailField(default='Ningun email registrado', max_length=254),
        ),
        migrations.AddField(
            model_name='grabador',
            name='email',
            field=models.EmailField(default='Ningun email registrado', max_length=254),
        ),
        migrations.AddField(
            model_name='ilustrador',
            name='email',
            field=models.EmailField(default='Ningun email registrado', max_length=254),
        ),
        migrations.AddField(
            model_name='pintor',
            name='email',
            field=models.EmailField(default='Ningun email registrado', max_length=254),
        ),
        migrations.AlterField(
            model_name='musico',
            name='email',
            field=models.EmailField(default='Ningun email registrado', max_length=254),
        ),
    ]
