# Generated by Django 4.2.4 on 2023-09-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salute_dArtist', '0003_actor_email_animador_email_cineasta_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Actor', 'verbose_name_plural': 'Actores'},
        ),
        migrations.AlterModelOptions(
            name='animador',
            options={'verbose_name': 'Animador', 'verbose_name_plural': 'Animadores'},
        ),
        migrations.AlterModelOptions(
            name='cineasta',
            options={'verbose_name': 'Cineasta', 'verbose_name_plural': 'Cineastas'},
        ),
        migrations.AlterModelOptions(
            name='escritor',
            options={'verbose_name': 'Escritor', 'verbose_name_plural': 'Escritores'},
        ),
        migrations.AlterModelOptions(
            name='escultor',
            options={'verbose_name': 'Escultor', 'verbose_name_plural': 'Escultores'},
        ),
        migrations.AlterModelOptions(
            name='fotografo',
            options={'verbose_name': 'Fotografo', 'verbose_name_plural': 'Fotografos'},
        ),
        migrations.AlterModelOptions(
            name='grabador',
            options={'verbose_name': 'Grabador', 'verbose_name_plural': 'Grabadores'},
        ),
        migrations.AlterModelOptions(
            name='ilustrador',
            options={'verbose_name': 'Ilustrador', 'verbose_name_plural': 'Ilustradores'},
        ),
        migrations.AlterModelOptions(
            name='musico',
            options={'verbose_name': 'Musico', 'verbose_name_plural': 'Musicos'},
        ),
        migrations.AlterModelOptions(
            name='pintor',
            options={'verbose_name': 'Pintor', 'verbose_name_plural': 'Pintores'},
        ),
        migrations.RemoveField(
            model_name='actor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='animador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cineasta',
            name='email',
        ),
        migrations.RemoveField(
            model_name='escritor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='escultor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='fotografo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='grabador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ilustrador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='musico',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pintor',
            name='email',
        ),
        migrations.AddField(
            model_name='actor',
            name='portfolio',
            field=models.URLField(default=' '),
        ),
        migrations.AddField(
            model_name='animador',
            name='portfolio',
            field=models.URLField(default=' '),
        ),
        migrations.AddField(
            model_name='cineasta',
            name='portfolio',
            field=models.URLField(default=' '),
        ),
        migrations.AddField(
            model_name='escritor',
            name='portfolio',
            field=models.URLField(default=' '),
        ),
        migrations.AddField(
            model_name='escultor',
            name='portfolio',
            field=models.URLField(default=' '),
        ),
        migrations.AddField(
            model_name='fotografo',
            name='portfolio',
            field=models.URLField(default=' '),
        ),
        migrations.AddField(
            model_name='grabador',
            name='portfolio',
            field=models.URLField(default=' '),
        ),
        migrations.AddField(
            model_name='ilustrador',
            name='portfolio',
            field=models.URLField(default=' '),
        ),
        migrations.AddField(
            model_name='musico',
            name='portfolio',
            field=models.URLField(default=' '),
        ),
        migrations.AddField(
            model_name='pintor',
            name='portfolio',
            field=models.URLField(default=' '),
        ),
    ]
