# Generated by Django 4.2.4 on 2023-09-03 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salute_dArtist', '0008_rename_serviciomusico_musicoservice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MusicoService',
            new_name='ServicioMusical',
        ),
    ]
