# Generated by Django 4.2.4 on 2023-09-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salute_dArtist', '0010_rename_serviciomusical_serviciomusicalmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioActorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=1000)),
                ('contacto', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ServicioAnimadorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=1000)),
                ('contacto', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ServicioCineastaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=1000)),
                ('contacto', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ServicioEscritorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=1000)),
                ('contacto', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ServicioEscultorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=1000)),
                ('contacto', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ServicioFotografoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=1000)),
                ('contacto', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ServicioGrabadorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=1000)),
                ('contacto', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ServicioIlustradorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=1000)),
                ('contacto', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ServicioPintorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=1000)),
                ('contacto', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='serviciomusicalmodel',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='serviciomusicalmodel',
            name='precio',
        ),
    ]
